name: chinos
favicon: null
layout_spectrum: 0.68425
typography_spectrum: 0.25798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09356761910021305
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
