name: chinos
favicon: null
layout_spectrum: 0.7071274984627962
typography_spectrum: 0.27484005503356457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09356761910021305
  lightness: 0.824493465013802
  saturation: 0.9941355548799038
  rhythmicContrast: 0.882692156592384
purpose: []
